name: preso_client
description: A new Flutter project with Serverpod.
version: "0.1.0"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ^3.6.1
  flutter: '>=3.19.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.3.1
  serverpod_auth_email_flutter: 2.3.1
  serverpod_auth_shared_flutter: 2.3.1
  serverpod_auth_wechat_flutter: 0.1.0
  preso_common: 0.1.0
  cupertino_icons: ^1.0.5
  get: ^5.0.0-release-candidate-9.3.2
dev_dependencies:
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true