name: preso_client
description: A new Flutter project with Serverpod.
version: "0.1.0"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ^3.6.1
  flutter: '>=3.19.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2 
  serverpod_flutter: 2.4.0
  serverpod_auth_email_flutter: 2.4.0
  serverpod_auth_shared_flutter: 2.4.0
  serverpod_auth_wechat_flutter: 2.4.0
  syncfusion_flutter_datagrid: ^28.2.6
  preso_common: 0.1.0
  cupertino_icons: ^1.0.5
  get: ^5.0.0-release-candidate-9.3.2
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  card_swiper: ^3.0.1
  flutter_dropzone: ^4.2.1
  dotted_border: ^2.1.0

  json_theme: 8.0.0+2
  dropdown_button2: ^2.3.9
  easy_sidemenu: ^0.6.1
  json_path: ^0.7.5
  trina_grid: ^1.6.6
  faker: ^2.2.0
  data_table_2: ^2.6.0
  
dev_dependencies:
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/themes/
    - assets/locales/