services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: preso
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - '6379:6379'
    command: redis-server --requirepass "V7YogaG9K2rnIpS1odXIKrqsW8kkfddt"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  db-data:
