name: preso_server
description: Starting point for a Serverpod server.
version: "0.1.0"

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  mailer: ^6.0.1
  serverpod: 2.4.0
  serverpod_auth_server: 2.4.0

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  serverpod_test: 2.4.0
  test: ^1.24.2
