name: preso_common
version: "0.1.0"
description: Starting point for a Serverpod client.

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  serverpod_client: 2.5.1 
  serverpod_auth_client: 2.5.1 
  serverpod_serialization: 2.5.1 
